### ISSUE TITLE
Add loading/options screen

### ISSUE THREAD

**Issue by papajohn** [berkeley-dsep-infra/interact#8]
Instead of having the interact link be a long-running HTTP request that brings the user directly to the directory/document being loaded, it should be a short-running request that loads a loading/options screen with the following elements
- [x] Progress bar that shows the different stages of interact: Ensure auth, Issue git fetch request
- [x] If user is not authenticated, redirect to Hub auth page and then back to the loading/options page
- [x] During git fetch, give option to show the log of that process
- [x] Estimated time to completion, perhaps based on other people loading the same content
- [x] When interact fails, say why and offer options for recovery (e.g., try the git fetch again)
- [x] Offer an option to download a zip of the content directly, along with some suggestion about how to open it
- [x] Offer an option to redirect to another JupyterHub running an interact server, so that the content gets loaded by that hub instead

It's important that this page is robust to people reloading it a bunch of times. The server should keep track of requests in progress (in memory dict should be fine) and when someone issues the same request 8 times, it should only execute once and show the loading status for that first request.

**Comment by papajohn** [comment]
Not all of these elements are high priority. The really critical ones are the top three.

Offering a download zip option would also be awesome. Unfortunately, it looks like generating a download link is harder than I hoped. Github doesn't support them directly. 

Someone made this service, `https://minhaskamal.github.io/DownGit/#/home`, but I tried it on `https://github.com/data-8/data8assets/tree/gh-pages/labs/lab01` and it failed with a 503 error.

**Comment by SamLau95** [comment]
It sounds like we'll want to move the server logic to something like [Tornado](http://www.tornadoweb.org/en/stable/) or [socket.io](https://github.com/socketio/socket.io) that can handle multiple connections at once + async operations (this is a must) and ideally stream back the progress to the user (not a must).

My understanding is that because we're using Flask right now even if we implement rendering a stub HTML page that hard refreshes to get progress, the server will be blocked by the long-running git commands. @ryanlovett does that sound right to you?

@papajohn Are you still looking for someone to work on this? I can put a word out if you'd like.

**Comment by ryanlovett** [comment]
Exactly right @samlau95. We should also use tornado since, IIRC, the new hub side service framework requires it. We'd get the hub auth stuff cheaply too.

**Comment by papajohn** [comment]
@alvinwan is taking a look this week, but probably can't continue. Let's see how much progress he and I can make before starting a search for someone else.

**Comment by alvinwan** [comment]
*Download link works with `http://`
